import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/navbar";
import {ClerkProvider} from "@clerk/nextjs";
import {Toaster} from "@/components/ui/sonner";
import {Suspense} from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Nelsh",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (

        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <Navbar/>
                    <Toaster />
                    <Suspense fallback={<p>hm</p>}>
                        {children}
                    </Suspense>
                </body>
            </html>
        </ClerkProvider>
    );
}
